services:
  comaho:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${COMAHO_PORT:-8080}:8080"
    volumes:
      - ${COMAHO_DOCKER_VOLUME_PATH:-./media}:/app/media
    environment:
      - COMAHO_PORT=${COMAHO_PORT:-8080}
      - COMAHO_DOCKER_VOLUME_PATH=${COMAHO_DOCKER_VOLUME_PATH}
    restart: "no"
    container_name: comaho
  test:
    build:
      context: .
      dockerfile: test.Dockerfile

volumes:
  comaho_data:
    driver: local
